name = "fce"
main = "index.js"
compatibility_date = "2024-11-23"

kv_namespaces = [
  { binding = "FCE_KV", id = "68ad7241a85343738ba873c7edbba092" }
]

[vars]
GITHUB_REPO = "RecSpeed/firmwareextrs"
GITHUB_WORKFLOW = "FCE.yml"
GITHUB_WORKFLOW_TAG = "auto"
